### PR TITLE
Add a cut plane schema

### PR DESCRIPTION
**Pull request by wizmer**
The cut plane is a JSON file that describes information about the plane
of cut of a particular experimental morphology.

I'd also like to add a contraint such that every experimental morphology maps
to maximum one cut plane instance but I don't know how to set that.

### CODE REVIEW

**Comment by slhill** [comment]
They’re related, but the cut plane is more specific and within the morphology coordinate space. This is used in the repair process.

**Comment by jdcourcol** [comment]
> They’re related, but the cut plane is more specific and within the morphology coordinate space. This is used in the repair process.
> […](#)
> Sent from my iPhone
> On Oct 4, 2018, at 04:10, Mohameth François SY ***@***.***> wrote: @MFSY requested changes on this pull request. Hi, Can you please give an example data for this schema ? Is the cut plane different from brain slicing plane ? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

@slhill  great to see you helping us on that.

**Comment by wizmer** [comment]
Sorry for being silent @MFSY 
The reason why I needed this ticket is evolving and I may no longer need it. I'll come back to you as soon as it is clarified.

**Comment by wizmer** [comment]
Yes, sure. I'll re-open it if needed with a reference to this one.

**Pull request closed without merging**
