### PR TITLE
EModelBuilding should use experimental morphology

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by jdcourcol** [comment]
Does that prevent an optimization to use a repaired cell ?

**Comment by genric** [comment]
> Does that prevent an optimization to use a repaired cell ?

Yes, I thought optimizations should only be using reconstructed cells.
Otherwise we need to relax this constraint and either use Entity or introduce some generic Morphology concept.

**Comment by jdcourcol** [comment]
> > Does that prevent an optimization to use a repaired cell ?
> 
> Yes, I thought optimizations should only be using reconstructed cells.
> Otherwise we need to relax this constraint and either use Entity or introduce some generic Morphology concept.

This is what we usually do. I don't know if it should be enforced. @wvangeit  do you have any input here ?

**Comment by wvangeit** [comment]
In the short term it's probably ok.
Also depends on what one defines as 'repaired'. There can always be a small postprocessing step that removes zero-length sections etc.
In the longer term we anyway need to allow for 'several' morphologies for 1 optimization.

**Comment by genric** [comment]
We discussed it with nexus team and looks like the best is to have root nsg:Morphology with experimental nsg:ReconstructedCell and simulation domain nsg:RepairedCell. Then in the emodel building activity we could just say generic nsg:Morphology. @wizmer any thoughts?

**Comment by wvangeit** [comment]
Makes sense. I anyway find this subclassing a bit arbitrary. Wouldn't it be better to add the state of the morph as an attribute ?

**Comment by genric** [comment]
These are not actual subclasses, they are more like tags. I guess @MFSY can better explain this.

**Comment by genric** [comment]
What do you think @annakristinkaufmann, @MFSY would it make sense to refactor Cell -> Morphology and migrate experimental data, to align the terminology?

**Comment by annakristinkaufmann** [comment]
I would be fine with changing to Morphology instead of Cell. Would require changing some schemas though.

**Comment by slhill** [comment]
I would suggest CellMorphology as there could eventually be morphologies of other entities as well.

Cheers
Sean

**Comment by slhill** [comment]
One additional point, there are already Glia Morphologies reconstructed from EM used in modeling the NGV. There will be many new kinds of morphologies (mitochondria , ER, etc)

**Comment by wvangeit** [comment]
@MFSY Ok, NeuronMorphology etc. makes sense

About the states. Yeah, I'm just thinking about cloned, mix-and-matched, zero-length-segment-removed etc. The morphology pipeline just has several stages, so 'repairedmorph' might be a bit broad. But for me it's ok like this.

About maxCount:1. Yes, Christian R has some experimental stuff where multiple morphs are used for 1 emodel. IMO this is the way to go in the future. For the moment tools like NMC portal, bluenaas etc will assume maxCount:1, so for me it's ok to leave it for now.

**Comment by genric** [comment]
So I removed the comment and, as I understand, we all agree to keep the `nsg:ReconstructedCell` in the `used`.

**Pull request merged**
