### PR TITLE
add brainRegion and species to model instance

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by apdavison** [comment]
I don't think we should have separate properties brainRegion and species, because they are not independent, rather we should refer to the brainRegion which in turn should reference the species.

**Comment by genric** [comment]
@MFSY how can we express that relationship between ontology terms? (Inferring species from brain region)

**Comment by jdcourcol** [comment]
@MFSY : one use case is to be able to say "I want to see all the hippocampus circuits".
and then get the list of rat or mouse (or whatever species) circuits. Is the proposal compatible with that ?

**Comment by apdavison** [comment]
ok, so I'm happy to merge this and then refactor later based on @mfsy's proposal

**Comment by genric** [comment]
I hope I got all the numbers correct :)

**Pull request merged**
