### PR TITLE
Deprecate ModelScript

### PR DESCRIPTION
**Pull request by wizmer**
as it is superseeded by EModelScript

### CODE REVIEW

**Comment by apdavison** [comment]
I think this change should be reverted. EModelScript is a subtype of ModelScript. We will have other subtypes in the near future.

**Comment by apdavison** [comment]
In general, I think PRs should be left open for at least a couple of days before merging, to allow time for discussion.

**Comment by MFSY** [comment]
Hi @apdavison,

This PR was approved (I did) because there is a newer version of the [ModelScript schema](https://github.com/INCF/neuroshapes/blob/master/modules/simulation/src/main/resources/schemas/neurosciencegraph/simulation/modelscript/v0.1.1.json) that can be used. The goal was not to remove ModelScript schema as far as I understand.

May be @wizmer  can comment on why he made this PR and if I understood correctly his intention.

**Comment by MFSY** [comment]
I also agree to give more time for PR review.

**Comment by genric** [comment]
In my understanding `modelscript` was split into `emodelscript` and `subcellularmodelscript`. They define exactly same shapes.

**Pull request merged**
